# Generated by Django 4.1.9 on 2023-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movies',
        ),
        migrations.AddField(
            model_name='addmovie',
            name='watchlistid',
            field=models.ManyToManyField(related_name='addmovies', to='movieapp.watchlist'),
        ),
        migrations.AlterField(
            model_name='addmovie',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
