# Generated by Django 4.2.4 on 2023-08-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_addmovie_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
