# Generated by Django 4.1.9 on 2023-08-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_watchlist_movies_addmovie_watchlistid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovie',
            name='watchlistid',
        ),
        migrations.AddField(
            model_name='addmovie',
            name='watchlistid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addmovies', to='movieapp.watchlist'),
            preserve_default=False,
        ),
    ]
