# Generated by Django 4.1.9 on 2023-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_addmovie_watchlistid_addmovie_watchlistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
