# Generated by Django 4.2.4 on 2023-09-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_alter_watchlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
